# Generated by Django 4.2 on 2023-05-09 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=127)),
                ("zip_code", models.CharField(max_length=9)),
                ("number", models.CharField(max_length=10)),
                ("complement", models.CharField(max_length=127, null=True)),
                ("is_main_address", models.BooleanField(default=False)),
            ],
        ),
    ]
