# Generated by Django 4.2 on 2023-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_is_admin_alter_user_is_saler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_saler",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
