# Generated by Django 4.2 on 2023-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_is_admin_alter_user_is_saler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_saler",
            field=models.BooleanField(default=False),
        ),
    ]
