# Generated by Django 4.2 on 2023-05-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="id_product",
            field=models.CharField(null=True),
        ),
    ]
