# Generated by Django 4.2 on 2023-05-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartproduct",
            name="id_product",
            field=models.CharField(null=True),
        ),
    ]
