# Generated by Django 4.2 on 2023-05-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="amount",
            field=models.IntegerField(null=True),
        ),
    ]
