# Generated by Django 4.2 on 2023-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.IntegerField()),
                ("name", models.CharField(max_length=127)),
                ("category", models.CharField(max_length=127)),
                ("available", models.BooleanField()),
            ],
        ),
    ]
